<?php
/**
 * @description Paradoteo Δράση 4 - Διαχείριση ηλεκτρονικών προσκλήσεων στελέχωσης μετακλητών θέσεων required data Settings
 * @author Fotis Routsis <fotis.routsis@gmail.com>, Themis Zamani <themiszamani@gmail.com>
 * @package drash4
 * @license http://joinup.ec.europa.eu/software/page/eupl EUPL Licence
 */

$data = array( 
	'sug_lastname' => array( 'id' => 'sug_lastname',
							'name' => 'sug_lastname',
							'required' => false,
							'requires_other' => true,
							'label' => 'Επώνυμο',
							'type' => 'text',
							'guide' => 'Το επώνυμό σας.',
							'show_guide' => false ),
	'sug_name' => array( 'id' => 'sug_name',
							'name' => 'sug_name',
							'required' => false,
							'requires_other' => true,
							'label' => 'Όνομα',
							'type' => 'text',
							'guide' => 'Το όνομά σας.',
							'show_guide' => false ),
	'sug_capacity' => array( 'id' => 'sug_capacity',
							'name' => 'sug_capacity',
							'required' => false,
							'requires_other' => true,
							'label' => 'Ιδιότητα',
							'type' => 'text',
							'guide' => 'Η ιδιότητά σας.',
							'show_guide' => false ),
	'sug_relation' => array( 'id' => 'sug_relation',
							'name' => 'sug_relation',
							'required' => false,
							'requires_other' => true,
							'label' => 'Σχέση με τον προτεινόμενο (επαγγελματική / συγγενική). Διεκρινίσατε',
							'type' => 'textarea',
							'guide' => 'Η σχέση σας με τον προτεινόμενο.',
							'show_guide' => false ),
	'sug_email' => array( 'id' => 'sug_email',
							'name' => 'sug_email',
							'required' => false,
							'requires_other' => true,
							'validate' => 'validate_email',
							'label' => 'Διεύθυνση Ηλεκτρονικού Ταχυδρομείου (e-mail)',
							'type' => 'text',
							'guide' => 'Το e-mail σας.',
							'show_guide' => false ),
	'sug_phone' => array( 'id' => 'sug_phone',
							'name' => 'sug_phone',
							'required' => false,
							'requires_other' => true,
							'label' => 'Τηλέφωνο',
							'type' => 'text',
							'guide' => 'Το τηλέφωνό σας.',
							'show_guide' => false ),
	'sug_is_aware' => array ( 'id' => 'sug_is_aware',
							'name' => 'sug_is_aware',
							'required' => false,
							'requires_other' => true,
							'label' => 'Είναι σε γνώση του προτεινόμενου η πρότασή σας;',
							'type' => '#yesno' ),
	'cand_lastname' => array( 'id' => 'cand_lastname',
							'name' => 'cand_lastname',
							'required' => false,
							'label' => 'Επώνυμο',
							'type' => 'text',
							'guide' => 'Το επώνυμό σας.',
							'show_guide' => true ),
	'cand_name' => array( 'id' => 'cand_name',
							'name' => 'cand_name',
							'required' => false,
							'label' => 'Όνομα',
							'type' => 'text',
							'guide' => 'Το όνομά σας.',
							'show_guide' => true ),
	'cand_fathername' => array( 'id' => 'cand_fathername',
							'name' => 'cand_fathername',
							'required' => false,
							'label' => 'Όνομα Πατέρα',
							'type' => 'text',
							'guide' => 'Το όνομα του πατέρα σας.',
							'show_guide' => true ),
	'cand_birthdate' => array( 'id' => 'cand_birthdate',
							'name' => 'cand_birthdate',
							'children' => array( 'day', 'month', 'year' ),
							'validate' => array( 'day' => 'validate_day',
												 'month' => 'validate_month',
												 'year' => 'validate_year' ),
							'required' => false,
							'label' => 'Ημερομηνία Γέννησης',
							'type' => '#date',
							'guide' => 'Η ημερομηνία γεννήσεώς σας.',
							'show_guide' => true ),
	'cand_nationality' => array( 'id' => 'cand_nationality',
							'name' => 'cand_nationality',
							'required' => false,
							'label' => 'Ιθαγένεια',
							'type' => 'text',
							'guide' => 'Η ιθαγένεια σας',
							'data' => 'ΕΛΛΗΝΙΚΗ',
							'show_guide' => true ),
	'cand_address' => array( 'id' => 'cand_address', 
							'name' => 'cand_address',
							'children' => array( 'road', 'number', 'city', 'country', 'areacode','region','municipality' ),
							'validate' => array( 'areacode' => 'validate_areacode' ),
							'required' => false,
							'label' => 'Διεύθυνση',
							'type' => '#address',
							'guide' => 'Η διεύθυνσή σας.',
							'show_guide' => true ),
	'cand_email' => array( 'id' => 'cand_email',
							'name' => 'cand_email',
							'required' => false,
							'not_required_when_is_recommended' => true,
							'validate' => 'validate_email',
							'label' => 'Διεύθυνση Ηλεκτρονικού Ταχυδρομείου (e-mail)',
							'type' => 'text',
							'guide' => 'Το e-mail σας. Προτείνεται να συμπληρώσετε το email σας για  να λάβετε αντίγραφο της φόρμας σας μετα την υποβολή.',
							'show_guide' => true ),
	'cand_phone_home' => array( 'id' => 'cand_phone_home',
							'name' => 'cand_phone_home',
							'required' => false,
							'not_required_when_is_recommended' => true,
							'label' => 'Τηλέφωνο Οικίας',
							'type' => 'text',
							'guide' => 'Το τηλέφωνο της οικίας σας.',
							'show_guide' => true ),
	'cand_phone_mobile' => array( 'id' => 'cand_phone_mobile',
							'name' => 'cand_phone_mobile',
							'required' => false,
							'not_required_when_is_recommended' => true,
							'label' => 'Κινητό Τηλέφωνο',
							'type' => 'text',
							'guide' => 'Το κινητό σας τηλέφωνο.',
							'show_guide' => true ),
	'cand_homepage' => array( 'id' => 'cand_homepage',
							'name' => 'cand_homepage',
							'label' => 'Διεύθυνση προσωπικής ιστοσελίδας / blog',
							'type' => 'text',
							'guide' => '(Αν υπάρχει).',
							'show_guide' => true ),
	'cand_lykeio_year' => array( 'id' => 'cand_lykeio_year',
							'name' => 'cand_lykeio_year',
							'required' => false,
							'label' => 'Έτος αποφοίτησης από το Λύκειο',
							'type' => 'text',
							'guide' => '(.',
							'show_guide' => false ),
	'cand_theseis_endiaferontos' => array( 'id' => 'cand_theseis_endiaferontos',
							'name' => 'cand_theseis_endiaferontos',
							'required' => false,
							'label' => 'Φορείς Ενδιαφέροντος', 
							'type' => 'textarea',
							'size' => 'large',
							'guide' => '',
							'show_guide' => true ),
	'cand_theseis_endiaferontos_logos' => array( 'id' => 'cand_theseis_endiaferontos_logos',
							'name' => 'cand_theseis_endiaferontos_logos',
							'required' => false,
							'label' => 'Για ποιο λόγο θεωρείτε τον εαυτό σας ικανό/ή για τους παραπάνω φορείς',
							'type' => 'textarea',
							'size' => 'large',
							'guide' => 'Για ποιο λόγο θεωρείτε τον εαυτό σας ικανό/ή για τους παραπάνω φορείς - Αναφέρατε για κάθε έναν ξεχωριστά',
							'show_guide' => true ),
	'cand_current_position' => array( 'id' => 'cand_current_position',
							'name' => 'cand_current_position',
							'required' => false,
							'label' => 'Θέση που κατέχετε τώρα',
							'type' => 'text',
							'guide' => 'Ο επίσημος τίτλος της θέσης που εργάζεστε τώρα',
							'show_guide' => true ),
	'cand_gg_protocol_id' => array( 'id' => 'cand_gg_protocol_id',
							'name' => 'cand_gg_protocol_id',
							'required' => false,
							'label' => '',
							'type' => 'text',
							'guide' => '',
							'show_guide' => false ),
	'cand_marital_status' => array( 'id' => 'cand_marital_status',
							'name' => 'cand_marital_status',
							'required' => false,
							'label' => 'Οικογενειακή κατάσταση',
							'type' => 'itemlist',
							'select_width' => "150",
							'datasource_table' => 'voc_marital_status',
							'datasource_ordertype' => 'none',
							'guide' => '',
							'show_guide' => false ),							
	'cand_no_of_children' => array( 'id' => 'cand_no_of_children',
							'name' => 'cand_no_of_children',
							'required' => false,
							'label' => 'Αριθμός τέκνων αν υπάρχουν',
							'type' => 'itemlist',
							'select_width' => "80",
							'datasource_table' => 'voc_no_of_children',
							'datasource_ordertype' => 'asc',
							'guide' => '',
							'show_guide' => false ),							
	'cand_years_of_experience' => array( 'id' => 'cand_years_of_experience',
							'name' => 'cand_years_of_experience',
							'required' => false,
							'label' => 'Έτη στην θέση που έχετε τώρα',
							'type' => 'text',
							'guide' => 'Πόσα έτη εργάζεστε στην θέση που έχετε τώρα',
							'show_guide' => true ),
	'cand_has_degree' => array( 'id' => 'cand_has_degree',
							'name' => 'cand_has_degree',
							'required' => false,
							'label' => 'Πτυχίο τριτοβάθμιας εκπαίδευσης',
							'type' => 'itemlist',
							'select_width' => "80",
							'datasource_table' => 'voc_yesno',
							'datasource_ordertype' => 'asc',
							'guide' => 'Επιλέξτε ναι ή όχι',
							'show_guide' => true ),							
	'cand_has_metaptixiako' => array( 'id' => 'cand_has_metaptixiako',
							'name' => 'cand_has_metaptixiako',
							'required' => false,
							'label' => 'Μεταπτυχιακές σπουδές',
							'type' => 'itemlist',
							'select_width' => "80",
							'datasource_table' => 'voc_yesno',
							'datasource_ordertype' => 'asc',
							'guide' => 'Επιλέξτε ναι ή όχι',
							'show_guide' => true ),							
	'cand_workexp_privatesector' => array( 'id' => 'cand_workexp_privatesector',
							'name' => 'cand_workexp_privatesector',
							'label' => 'Διοικητική εμπειρία σε θέση ευθύνης του Ιδιωτικού Τομέα, (χρόνια)',
							'type' => 'itemlist',
							'select_width' => "80",
							'datasource_table' => 'voc_years',
							'datasource_ordertype' => 'asc',
							'guide' => 'Επιλέξτε έτη επαγγελματικής εμπειρίας',
							'show_guide' => true ),							
	'cand_workexp_publicsector' => array( 'id' => 'cand_workexp_publicsector',
							'name' => 'cand_workexp_publicsector',
							'label' => 'Διοικητική εμπειρία σε θέση ευθύνης του Δημόσιου Τομέα, (χρόνια)',
							'type' => 'itemlist',
							'select_width' => "80",
							'datasource_table' => 'voc_years',
							'datasource_ordertype' => 'asc',
							'guide' => 'Επιλέξτε έτη επαγγελματικής εμπειρίας',
							'show_guide' => true ),							
	'cand_work_fulltime' => array( 'id' => 'cand_work_fulltime',
							'name' => 'cand_work_fulltime',
							'required' => false,
							'label' => 'Η διαθεσιμότητα απασχόλησης είναι πλήρης;',
							'type' => 'itemlist',
							'select_width' => "80",
							'datasource_table' => 'voc_yesno',
							'datasource_ordertype' => 'asc',
							'guide' => 'Πλήρης, π.χ , Διοίκηση ή <br> Μερική, π.χ. Μέλος Δ.Σ',
							'show_guide' => true ),							
	'cand_gender' => array( 'id' => 'cand_gender',
							'name' => 'cand_gender',
							'required' => false,
							'label' => 'Φύλο',
							'type' => 'itemlist',
							'select_width' => "80",
							'datasource_table' => 'voc_genders',
							'datasource_ordertype' => 'none',
							'guide' => 'Επιλέξτε φύλο',
							'show_guide' => true ),							
	'cand_occupation_type' => array( 'id' => 'cand_occupation_type',
							'name' => 'cand_occupation_type',
							'required' => false,
							'label' => 'Τρέχουσα Απασχόληση',
							'type' => 'itemlist',
							'select_width' => "250",
							'datasource_table' => 'voc_occupation_types',
							'datasource_ordertype' => 'asc',
							'guide' => 'Επιλέξτε τρέχουσα απασχόληση',
							'show_guide' => true ),							
	'cand_vocation' => array( 'id' => 'cand_vocation',
							'name' => 'cand_vocation',
							'required' => false,
							'label' => 'Επαγγελματική κατηγορία / Επάγγελμα',
							'type' => 'itemlist',
							'select_width' => "400",
							'datasource_table' => 'voc_vocations',
							'datasource_ordertype' => 'asc',
							'guide' => 'Παρακαλούμε επιλέξτε την κατηγορία επαγγέλματος στην οποία εργάζεστε ή ειδικεύεστε',
							'show_guide' => true ),							
	'cand_vocation_other' => array( 'id' => 'cand_vocation_other',
							'name' => 'cand_vocation_other',
							'required' => false,
							'validate' => 'validate_vocation_other',
							'not_required_when_is_recommended' => true,
							'label' => 'Άλλο επάγγελμα', 
							'type' => 'text',
							'guide' => 'Αν δεν υπάρχει στην παραπάνω λίστα παρακαλούμε εισάγετε το επάγγελμά σας εδώ',
							'show_guide' => true ),
	'cand_edu_level' => array( 'id' => 'cand_edu_level',
							'name' => 'cand_edu_level',
							'required' => false,
							'label' => 'Εκπαίδευση και Κατάρτιση',
							'type' => 'itemlist',
							'select_width' => "250",
							'datasource_table' => 'voc_edu_levels',
							'datasource_ordertype' => 'none',
							'guide' => 'Παρακαλούμε επιλέξτε το επίπεδο της εκπαίδευσής σας. <br>'.
										'Πρώτα συμπληρώστε προπτυχιακές και κατόπιν τυχόν μεταπτυχιακές σπουδές ',
							'show_guide' => true ),							
	'cand_lang_mother1' => array( 'id' => 'cand_lang_mother1',
							'name' => 'cand_lang_mother1',
							'required' => false,
							'label' => 'Μητρική γλώσσα',
							'type' => 'itemlist',
							'data' => 'Ελληνικά',
							'select_width' => "300",
							'datasource_table' => 'voc_languages',
							'datasource_ordertype' => 'asc',
							'guide' => 'Παρακαλούμε επιλέξτε την μητρική σας γλώσσα',
							'show_guide' => true ),							
	'cand_lang_mother2' => array( 'id' => 'cand_lang_mother2',
							'name' => 'cand_lang_mother2',
							'required' => false,
							'label' => 'Δεύτερη μητρική γλώσσα',
							'type' => 'itemlist',
							'select_width' => "300",
							'datasource_table' => 'voc_languages',
							'datasource_ordertype' => 'asc',
							'guide' => 'Παρακαλούμε επιλέξτε την δεύτερη μητρική σας γλώσσα (εάν υπάρχει)',
							'show_guide' => true ),							
	'cand_form_acceptance' => array( 'id' => 'cand_form_acceptance',
							'name' => 'cand_form_acceptance',
							'required' => false,
							'label' => 'Ο αιτών/η αιτούσα δηλώνει υπεύθυνα ότι όλα τα αναφερόμενα στοιχεία είναι<br>'. 
										'αληθή και ότι αποδέχεται την περαιτέρω χρήση τους για το σκοπό της<br>'.
										'παρούσας εκδήλωσης ενδιαφέροντος.',
							'type' => 'itemlist',
							'select_width' => "80",
							'datasource_table' => 'voc_yes',
							'datasource_ordertype' => 'asc',
							'guide' => '',
							'show_guide' => false ),							
	'cand_email_verification' => array( 'id' => 'cand_email_verification',
							'name' => 'cand_email_verification',
							'required' => false,
							'label' => 'Επιβεβαίωση σωστής αναγραφής ηλ. διεύθυνσης (e-mail)',
							'type' => 'itemlist',
							'select_width' => "140",
							'datasource_table' => 'voc_confirm_email',
							'datasource_ordertype' => 'asc',
							'guide' => 'Eπιβεβαιώνω  τη  σωστή αναγραφή της παραπάνω  ηλεκτρονική διεύθυνσης μου ( e-mail)',
							'show_guide' => true ),						
	'cand_languages' => array( 'id' => 'cand_languages',
					'name' => 'cand_languages',
					'required' => false,
					'label' => 'Ξένες Γλώσσες και ικανότητα χρήσης.',
					'type' => 'textarea',
					'size' => 'large',
					'guide' => 'Επίπεδο γνώσης γιά:<br>Αγγλικά,Γαλλικά,Γερμανικά,<br>Ισπανικά,Ιταλικά,Άλλη<br>( Επίπεδα: Άριστα,Πολύ καλά,Καλά,Στοιχειώδης)',
					'show_guide' => true ),
	'cand_computers' => array( 'id' => 'cand_computers',
					'name' => 'cand_computers',
					'required' => false,
					'label' => 'Συμπληρώστε αν επιθυμείτε πρόσθετα στοιχεία για  τις γνώσεις σε ΤΠΕ',
					'type' => 'textarea',
					'size' => 'large',
					'guide' => 'Τεχνολογίες Πληροφορικής και Επικοινωνιών : Επίπεδο γνώσης εφαρμογών αυτοματισμου γραφείου, βάσεις δεδομένων και εφαρμογών διαδικτύου ( Επίπεδα: Άριστο,Πολύ καλό,Καλό,Στοιχειώδες )',
					'show_guide' => false ),
	'cand_edu' => array( 'id' => 'cand_edu',
					'name' => 'cand_edu',
					'required' => false,
					'label' =>	'Συμπληρώστε αν χρειάζεται πρόσθετα στοιχεία για τις σπουδές σας',
					'type' => 'textarea',
					'size' => 'large',
					'guide' =>  '',
					'show_guide' => false  ),
	'cand_simple_statement' => array( 'id' => 'cand_simple_statement',
					'name' => 'cand_simple_statement',
					'required' => false,
					'label' => 'Σύντομη Δήλωση Ενδιαφέροντος: (300 λέξεις μέγιστο)',
					'type' => 'textarea',
					'size' => 'large',
					'guide' =>  '(300 λέξεις μέγιστο)',
					'show_guide' => false  ),
	'cand_edu_publications' => array( 'id' => 'cand_edu_publications',
					'name' => 'cand_edu_publications',
					'required' => false,
					'label' => 'Δημοσιεύσεις',
					'type' => 'textarea',
					'size' => 'large',
					'guide' =>  '',
					'show_guide' => false  ),
	'cand_prof' => array( 'id' => 'cand_prof',
					'name' => 'cand_prof',
					'required' => false,
					'label' => 'Συμπληρώστε αν χρειαστεί πρόσθετα στοιχεία για την εργασιακή σας εμπειρία',
					'type' => 'textarea',
					'size' => 'large',
					'guide' => 'Από…. έως ….'.
					'<br>Απασχόληση στη θέση που κατείχατε'.
					'<br>Κύριες δραστηριότητες και αρμοδιότητες'.
					'<br>Επωνυμία Εργοδότη'.
					'<br>Άμεσος προϊστάμενος (και στοιχεία επικοινωνίας)'.
					'<br>(επαναλαμβάνεται όσες φορές χρειάζεται)',
					'show_guide' => false ),
	'cand_prof_array' => array( 'id' => 'cand_prof_array',
						'name' => 'cand_prof_array',
						'required' => false,
						'not_required_when_is_recommended' => true,
						'children' => array( 'period_from', 'period_to', 'position', 'activities', 'employer_name', 'employer_city',  'employer_postcode', 'employer_type' ),
						'multiple' => true,
						'min_count' => 1,
						'label' => 'Επαγγελματική πείρα',
						'type' => '#prof_array',
						'guide' => 'Αναφέρατε τις εταιρείες/οργανισμούς που εργαστήκατε.' ),	
	'cand_edu_array' => array( 'id' => 'cand_edu_array',
						'name' => 'cand_edu_array',
						'required' => false,
						'not_required_when_is_recommended' => true,
						'children' => array( 'period_from', 'period_to', 'title', 'skills', 'organisation', 'level','final_grade' ),
						'multiple' => true,
						'min_count' => 0,
						'label' => 'Πτυχίο, πιστοποιητικό ή δίπλωμα',
						'type' => '#edu_array',
						'guide' => 'Αναφέρατε πιστοποιητικά ή διπλώματα' ),	
	'cand_edu_ba_array' => array( 'id' => 'cand_edu_ba_array',
						'name' => 'cand_edu_ba_array',
						'required' => false,
						'not_required_when_is_recommended' => true,
						'children' => array( 'country', 'name','name_other', 'department', 'year_from', 'year_to', 'final_grade', 'comments' ),
						'multiple' => true,
						'min_count' => 0,
						'label' => 'Προπτυχιακές σπουδές',
						'type' => '#edu_ba_array',
						'guide' => 'Προπτυχιακές σπουδές - Σημειώστε συμπληρωματικά στοιχεία σε περίπτωση που το επιθυμείτε.' ,
						'show_guide' => false ),	
	'cand_edu_further_array' => array( 'id' => 'cand_edu_further_array',
						'name' => 'cand_edu_further_array',
						'required' => false,
						'not_required_when_is_recommended' => true,
						'children' => array( 'country', 'name','name_other', 'department', 'year_from', 'year_to', 'final_grade', 'comments', 'title' ),
						'multiple' => true,
						'min_count' => 0,
						'label' => 'Μεταπτυχιακές σπουδές',
						'type' => '#edu_further_array',
						'guide' => 'Μεταπτυχιακές σπουδές - Σημειώστε συμπληρωματικά στοιχεία σε περίπτωση που το επιθυμείτε.' ,
						'show_guide' => false ),	
	'cand_lang_simple_array' => array( 'id' => 'cand_lang_simple_array',
						'name' => 'cand_lang_simple_array',
						'required' => false,
						'not_required_when_is_recommended' => true,
						'children' => array('language', 'level' ),
						'multiple' => true,
						'min_count' => 0,
						'label' => 'Ξένη Γλώσσα',
						'type' => '#lang_simple_array',
						'guide' => 'Αναφέρατε τις γλώσσες και τα επίπεδα γνώσης που έχετε για κάθε μία.</a>' ),	
	'cand_computers_array' => array( 'id' => 'cand_computers_array',
						'name' => 'cand_computers_array',
						'required' => false,
						'not_required_when_is_recommended' => true,
						'children' => array('word_processing', 'databases', 'spreadsheets', 'networks', 'internet' ),
						'multiple' => true,
						'min_count' => 1,
						'label' => 'Γνώση Χρήσης ΤΠΕ',
						'type' => '#computers_array',
						'guide' => 'Τεχνολογίες Πληροφορικής και Επικοινωνιών : Επίπεδο γνώσης εφαρμογών αυτοματισμου γραφείου, βάσεις δεδομένων και εφαρμογών διαδικτύου ( Επίπεδα: Άριστο,Πολύ καλό,Καλό,Στοιχειώδες )' ),	
	'cand_social_activity' => array( 'id' => 'cand_social_activity',
					'name' => 'cand_social_activity',
					'required' => false,
					'label' => 'Κοινωνική Δραστηριότητα.',
					'type' => 'textarea',
					'size' => 'large' ),
	'cand_political_activity' => array( 'id' => 'cand_political_activity',
					'name' => 'cand_political_activity',
					'required' => false,
					'label' => 'Πολιτική Δραστηριότητα.',
					'type' => 'textarea',
					'size' => 'large' ),
	'cand_directing_exp' => array( 'id' => 'cand_directing_exp',
					'name' => 'cand_directing_exp',
					'required' => false,
					'label' => 'Διοικητική εμπειρία.',
					'type' => 'textarea',
					'size' => 'large' ),
	'final_confirmation' => array( 'id' => 'final_confirmation',
					'name' => 'final_confirmation',
					'required' => true,
					'label' => 'Έχετε συμπληρώσει όλα τα πεδία που επιθυμείτε στις παραπάνω καρτέλες?',
					'type' => 'itemlist',
					'select_width' => "80",
					'datasource_table' => 'voc_yes',
					'datasource_ordertype' => 'asc',
					'guide' => '',
					'show_guide' => false ),					
	'cand_reco' => array( 'id' => 'cand_reco',
						'name' => 'cand_reco',
						'required' => false,
						'not_required_when_is_recommended' => true,
						'children' => array( 'lastname', 'name', 'service', 'subject', 'from', 'to', 'coop_type', 'phone', 'email' ),
						'multiple' => true,
						'min_count' => 2,
						'label' => 'Συστήνων',
						'type' => '#reco',
						'guide' => 'Αναφέρατε τα στοιχεία των προσώπων που μπορούν να δώσουν συστάσεις για τον υποψήφιο, αν τους ζητηθεί.' ),	
	'null' => array()
	);

foreach ( $data as &$row ) {
 $row[ 'invalid' ] = array(); 
 if (isset( $_SESSION[ 'is_recommended' ] ) && $_SESSION[ 'is_recommended' ])
 {
	if (array_key_exists( 'not_required_when_is_recommended', $row ) && $row[ 'not_required_when_is_recommended' ])
	{
		$row['required'] = false;
	}
 }

 }

?>
